.\" Process this file with
.\" groff -man -Tascii git-build-state.1
.\"
.hw build-state.format.log build-state.format.state
.TH GIT-BUILD-STATE 1 "NOV 2016" git-build-state "User Manuals"
.SH NAME
git-build-state \- Display build state from Stash/Bitbucket
.\-------------------------------- SYNOPSIS ------------------------------------
.SH SYNOPSIS
.I git build-state
[options] [-log] <commit>
.\------------------------------ DESCRIPTION -----------------------------------
.SH DESCRIPTION
Show build state stored in Stash/Bitbucket for commit.

Commits can be on any form that `git show' can translate to a commit.

It is also possible to display a `git log' with build stats included.
.\-------------------------------- OPTIONS -------------------------------------
.SH OPTIONS
.IP -log
Show the git log with build stats included.
.IP "-format <template>"
Formats the output with Go's text/template. See \fI build-state.format.log \fR and \fI build-state.format.state \fR for more information.
.IP -json
Format output as JSON.
.IP -install
Sets up Bash completion, manual mapages, and authentication
.IP "-proto <http|https>"
Override the protocoll used with Stash/Bitbucket. This should only be used for development.
.IP -generate-creds
Use this for generating credentials necessary to communicate with Stash/Bitbucket

.\----------------------------- CONFIGURATION ----------------------------------
.SH CONFIGURATION
Configuration is done with `git config`. Example to set build-state.auth.user configuration:
.RS
.B git config --global build-state.auth.user user@example.com
.RE

.I build-state.auth.user
.RS
The username for authentications
.RE

.I build-state.auth.credentials
.RS
Base64 encoded string of username and password. Encoded on the form \fI username:password\fR. This might seem insecure, however it should not be worse the having a unencrypted token saved.
.RE

.I build-state.endpoint
.RS
Normaly the Stash/Bitbucket URL is inferred from the git remote setting. This setting will over ride that. Written on the form \fI https://example.com
.RE

.I build-state.port
.RS
Defines the port for the Stash/Bitbucket API
.RE

.I build-state.format.log
.RS
Template definition of the output for the log. The default template definition:
.nf
{{.ID}} {{.Message}}
   Successful: {{.Status.Successful}},
   In Progress: {{.Status.InProgress}},
   Failed: {{.Status.Failed}}
.fi
.RE

.I build-state.format.state
.RS
Template definition of the output for the build state. The default template definition:

.nf
Name:  {{.Name}}     Key: {{.Key}}
State: {{.State}}
URL:   {{.URL}}
Date:  {{.DateAdded}}

   {{.Description}}
.fi
.RE
.\-------------------------------- AUTHOR --------------------------------------
.SH AUTHOR
Nils Lagerkvist <nils dot lagerkvist at gmail dot com>
